name: Jest

on:
  push:
    branches:
      - canary
jobs:
  jest-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install
        run: sudo npm i -g npm@latest &&  npm install --force

      - name: TEST
        run: npm run test:coverage

